name: Build Production

on:
  push:
    branches: ["main"]
    paths:
      - "apps/mobile/**"

jobs:
  build_android:
    name: Build Android Production
    type: build
    params:
      platform: android
      profile: production
      message: "Production build from main"

  build_ios:
    name: Build iOS Production
    type: build
    params:
      platform: ios
      profile: production
      message: "Production build from main"

  notify_completion:
    name: Build Complete
    needs: [build_android, build_ios]
    type: doc
    params:
      md: |
        # Production Builds Complete

        Both Android and iOS production builds are ready.

        ## Build Details
        - **iOS Build ID**: ${{ needs.build_ios.outputs.build_id }}
        - **Android Build ID**: ${{ needs.build_android.outputs.build_id }}
        - **Version**: ${{ needs.build_ios.outputs.app_version }}

        ## Next Steps
        When ready to submit to app stores, you can manually submit these builds from the EAS dashboard or enable the submission workflow.
