name: Build and Submit to App Stores

on:
  push:
    branches: ["main"]

defaults:
  working_directory: apps/mobile

jobs:
  build_android:
    name: Build Android Production
    type: build
    params:
      platform: android
      profile: production
      message: "Production build for store submission"

  build_ios:
    name: Build iOS Production
    type: build
    params:
      platform: ios
      profile: production
      message: "Production build for store submission"

  submit_android:
    name: Submit to Google Play
    type: submit
    needs: [build_android]
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production

  submit_ios:
    name: Submit to App Store
    type: submit
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production

  notify_completion:
    name: Submission Complete
    needs: [submit_android, submit_ios]
    type: doc
    params:
      md: |
        # Submission Complete

        Both Android and iOS builds have been submitted to their respective app stores.

        ## Next Steps

        ### iOS (App Store Connect)
        1. Go to [App Store Connect](https://appstoreconnect.apple.com)
        2. Navigate to the Laurel app
        3. Select the new build for TestFlight or App Store review
        4. Add release notes and submit for review

        ### Android (Google Play Console)
        1. Go to [Google Play Console](https://play.google.com/console)
        2. Navigate to the Laurel app
        3. The build is available in the Internal testing track
        4. Promote to other tracks when ready

        ## Build Details
        - **iOS Build ID**: ${{ needs.build_ios.outputs.build_id }}
        - **Android Build ID**: ${{ needs.build_android.outputs.build_id }}
        - **Version**: ${{ needs.build_ios.outputs.app_version }}
